// Generated by scripts/port-hybrid.py from new-design/hybrid-src (the Claude Design canvas). Do not edit by hand.
/* eslint-disable */
import { ramp, type Cfg, type Mv } from "./engine";

export const s01b: Cfg = { W: 800, H: 800, N: 2400, T: 12,
regions:function(G){ var s=1.0; var r=[];
    r.push({tag:'p0',pts:G.cluster(-250*s,-180*s,70*s,260)}); r.push({tag:'p1',pts:G.cluster(230*s,-120*s,70*s,260)}); r.push({tag:'p2',pts:G.cluster(60*s,230*s,70*s,260)});
    r.push({tag:'core',pts:G.hex(0,0,100*s,300)});
    [-90,30,150].forEach(function(a,i){ var A=a*Math.PI/180; r.push({tag:'c'+i,pts:G.hex(430*s*Math.cos(A),430*s*Math.sin(A),70*s,180)}); });
    r.push({tag:'r0',pts:G.line(-250*s,330*s,-110*s,330*s,80)}); r.push({tag:'r1',pts:G.line(-70*s,330*s,70*s,330*s,80)}); r.push({tag:'r2',pts:G.line(110*s,330*s,250*s,330*s,80)});
    return r; },
  moves:function(G){ var s=1.0; var m: Mv[] = []; ['p0','p1','p2'].forEach(function(tg,i){ m.push({tag:tg,at:2.6+i*0.15,dur:1.0,to:G.cluster(0,0,80*s,300)}); });
    [-90,30,150].forEach(function(a,i){ var A=a*Math.PI/180; m.push({tag:'c'+i,at:4.6+i*0.8,dur:0.9,to:G.hex(200*s*Math.cos(A),200*s*Math.sin(A),70*s,300)}); }); return m; },
  light:function(tag,t,p,C){ var R=t>=11.4;
    if(tag[0]==='p'){ if(R) return [C.ink3,0.7]; if(t<2.6) return [C.ink3,0.7]; return [C.amber2, t<3.6?0.8:0.5]; }
    if(tag==='core'){ var on=t>=3.6&&!R; return [C.amber, on?1:0]; }
    if(tag[0]==='c'){ var i=+tag[1]; var on=t>=4.6+i*0.8&&!R; return [C.ink2, on?0.9:0]; }
    if(tag[0]==='r'){ var i=+tag[1]; var t0=8.0+i*0.8; var on=t>=t0&&!R; var u=Math.min(1,(t-t0)/0.5); return [on&&p.u<=u?C.ink1:C.line2, on?(p.u<=u?1:0.5):0.45]; }
    return [C.line2,0]; }
};

export const s02a: Cfg = { W: 800, H: 800, N: 2400, T: 11,
regions:function(G){ var s=1.0; return [
    {tag:'d1',pts:G.rect(-300*s,-180*s,150*s,90*s,220)},{tag:'d2',pts:G.rect(-300*s,0,150*s,90*s,220)},{tag:'d3',pts:G.rect(-300*s,180*s,150*s,90*s,220)},
    {tag:'hex',pts:G.hex(40*s,0,130*s,420)},{tag:'core',pts:G.cluster(40*s,0,110*s,380)},
    {tag:'l1',pts:G.line(-222*s,-170*s,-80*s,-50*s,120)},{tag:'l2',pts:G.line(-222*s,0,-92*s,0,120)},{tag:'l3',pts:G.line(-222*s,170*s,-80*s,50*s,120)},
    {tag:'a1',pts:G.line(200*s,-56*s,380*s,-56*s,150)},{tag:'a2',pts:G.line(200*s,0,380*s,0,150)},{tag:'a3',pts:G.line(200*s,56*s,340*s,56*s,150)}
  ];},
  light:function(tag,t,p,C){
    var dim=C.line2, A=0.9;
    if(tag==='d1'){ return [t>=1.6&&t<10.4?C.ink2:C.ink3, A]; }
    if(tag==='d2'){ return [t>=2.2&&t<10.4?C.ink2:C.ink3, A]; }
    if(tag==='d3'){ var on=t>=2.8&&t<3.3; return [on?C.ink2:C.ink3, on?A:0.55]; }
    if(tag==='l1'||tag==='l2'||tag==='l3'){
      var t0=tag==='l1'?1.6:tag==='l2'?2.2:2.8; var u=(t-t0)/0.8; var pos=p.u;
      if(t<t0||t>10.4) return [dim,0.5];
      if(tag==='l3'){ if(u<1){ var near=Math.abs(pos-u*0.55)<0.08; return [near?C.alert:dim, near?1:0.5]; } return [dim,0.35]; }
      if(u<1){ var near=Math.abs(pos-u)<0.08; return [near?C.amber:dim, near?1:0.5]; }
      return [C.amber2, 0.55];
    }
    if(tag==='hex'){ var on=t>=3.5&&t<10.4; return [on?C.amber:C.ink3, on?1:0.8]; }
    if(tag==='core'){ var on=t>=3.6&&t<10.4; return [C.amber2, on?0.45:0]; }
    if(tag==='a1'||tag==='a2'||tag==='a3'){ var t0=tag==='a1'?5.0:tag==='a2'?5.8:6.6; var on=t>=t0&&t<10.4; var u=Math.min(1,(t-t0)/0.5); var lit=on&&p.u<=u; return [lit?C.ink1:dim, lit?1:0.45]; }
    return [dim,0];
  }
};

export const s03b: Cfg = { W: 800, H: 800, N: 2400, T: 12,
regions:function(G){ var s=1.0; var r=[]; r.push({tag:'bd',pts:G.hex(140*s,60*s,180*s,520)}); r.push({tag:'ev',pts:G.cluster(-300*s,120*s,70*s,220)});
    [-200,0,200].forEach(function(x,i){ r.push({tag:'m'+i,pts:G.cluster(x*s,-310*s,60*s,200)}); r.push({tag:'f'+i,pts:G.line(-280*s,100*s,x*s,-290*s,70)}); }); return r; },
  moves:function(G){ var s=1.0; return [{tag:'m2',at:6.4,dur:1.2,to:G.cluster(140*s,60*s,90*s,300)}]; },
  light:function(tag,t,p,C){ var R=t>=11.4; var dim=C.line2;
    if(tag==='ev') return [t>=0.4&&!R?C.ink2:C.ink3,0.9];
    if(tag[0]==='f'){ var i=+tag[1]; var t0=1.2+i*0.3; if(R||t<t0) return [dim,0]; var u=(t-t0)/0.9; if(u<1){ var near=Math.abs(p.u-u)<0.07; return [near?C.amber:dim, near?1:0.35]; } return [dim,t<5.0?0.3:0]; }
    if(tag[0]==='m'){ var i=+tag[1]; if(R) return [C.ink3,0.6]; var score=[0.7,0.5,1.0][i]; var u=Math.max(0,Math.min(1,(t-2.6)/2.0)); if(i===2&&t>=4.8) return [C.amber, t>=9.2?1:0.95]; return [t<2.6?C.ink3:C.ink2, 0.4+0.6*score*u]; }
    if(tag==='bd'){ if(R) return [C.ink3,0.3]; return [t>=8.0?C.ok:C.ink3, t<5.4?0.3:0.9]; }
    return [dim,0]; }
};

export const s04b: Cfg = { W: 1600, H: 400, N: 2400, T: 12,
regions:function(G){ var s=1.0, sy=1.0; var r=[];
    r.push({tag:'nb',pts:G.rect(-560*s,0,180*s,110*sy,420)}); r.push({tag:'nbx',pts:G.cluster(-560*s,0,200*s,120)});
    [-240,0,240,480].forEach(function(x,i){ r.push({tag:'c'+(i+1),pts:G.hex(x*s,300*sy,70*s,170)}); });
    r.push({tag:'k1',pts:G.line(-170*s,300*sy,-70*s,300*sy,90)}); r.push({tag:'k2',pts:G.line(70*s,300*sy,170*s,300*sy,90)}); r.push({tag:'k3',pts:G.line(310*s,300*sy,410*s,300*sy,90)});
    r.push({tag:'door',pts:G.line(150*s,-48*sy,150*s,48*sy,60)}); r.push({tag:'ceil',pts:G.line(180*s,-112*sy,300*s,-112*sy,60)}); r.push({tag:'trace',pts:G.line(180*s,146*sy,560*s,146*sy,80)});
    r.push({tag:'pk',pts:G.cluster(0,0,26*s,90)}); r.push({tag:'rq',pts:G.cluster(0,0,16*s,40)}); return r; },
  moves:function(G){ var s=1.0, sy=1.0; var m: Mv[] = []; [-240,0,240,480].forEach(function(x,i){ m.push({tag:'c'+(i+1),at:2.6+i*0.8,dur:0.9,to:G.hex(x*s,0,70*s,300)}); });
    [[-170,-70],[70,170],[310,410]].forEach(function(l,i){ m.push({tag:'k'+(i+1),at:3.2+i*0.8,dur:0.7,to:G.line(l[0]*s,0,l[1]*s,0,200)}); });
    m.push({tag:'nb',at:2.6,dur:1.2,to:G.rect(-560*s,0,700*s,300*sy,500)}); m.push({tag:'nbx',at:2.6,dur:1.2,to:G.rect(-560*s,0,700*s,300*sy,200)}); return m; },
  dynamic:{
    pk:function(t){ var s=1.0; var xs=[-240,0,240,480]; var i=t<7?0:t<8?0:t<9?1:t<10?2:3; var u=t<7?0:t<10?ramp(t,7+i,8+i):1; var sm=u*u*(3-2*u); return [(xs[i]+(xs[Math.min(3,i+1)]-xs[i])*(t<10?sm:0))*s,0]; },
    rq:function(t){ var s=1.0, sy=1.0; var u=ramp(t,10.2,11.0); var sm=u*u*(3-2*u); return [(760-(760-240)*sm)*s,(-70+70*sm)*sy]; }
  },
  light:function(tag,t,p,C){ var dim=C.line2, R=t>=11.6;
    if(tag==='nb'){ if(R||t<2.6) return [C.ink3,0.85]; return [C.ink3, Math.max(0,0.85-(t-2.6)*0.9)]; }
    if(tag==='nbx'){ if(R||t<2.6) return [C.alert,0.6]; return [C.alert, Math.max(0,0.6-(t-2.6)*0.7)]; }
    if(tag[0]==='c'&&tag.length===2){ var i=+tag[1]-1; if(R||t<2.6+i*0.8) return [dim,0]; var arrive=7+i, leave=8+i; if(t<arrive) return [C.ink3,0.85]; if(t<leave) return [C.amber,1]; if(i===2&&t>=10.9&&t<11.3) return [C.amber,1]; return [C.ok,0.95]; }
    if(tag[0]==='k'){ var i=+tag[1]; if(R||t<3.2+(i-1)*0.8) return [dim,0]; var u=ramp(t,7+i-1+0.6,7+i-1+1.0); return [u>0?C.amber2:C.ink3,0.75]; }
    if(tag==='door'){ var on=t>=5.8&&!R; var hot=t>=10.8&&t<11.2; return [hot?C.ok:C.ink2, on?0.9:0]; }
    if(tag==='ceil'){ var on=t>=6.4&&!R; return [C.ink2, on?0.9:0]; }
    if(tag==='trace'){ var on=t>=7.0&&!R; var u=ramp(t,11.0,11.5); var lit=on&&t>=11.0&&p.u<=u; return [lit?C.ink1:C.ink2, on?(lit?1:0.7):0]; }
    if(tag==='pk'){ var on=t>=6.9&&t<10.6&&!R; return [C.amber, on?1:0]; }
    if(tag==='rq'){ var on=t>=10.2&&t<11.1&&!R; return [C.ink1, on?1:0]; }
    return [dim,0]; }
};

export const s05b: Cfg = { W: 800, H: 800, N: 2400, T: 12,
regions:function(G){ var s=1.0; var r=[]; r.push({tag:'h0',pts:G.hex(0,0,70*s,220)});
    for(var i=0;i<6;i++){ var a=i*Math.PI/3; var x=175*s*Math.cos(a), y=175*s*Math.sin(a); r.push({tag:'c'+i,pts:G.hex(x,y,70*s,150)}); r.push({tag:'l'+i,pts:G.line(70*s*Math.cos(a),70*s*Math.sin(a),x-70*s*Math.cos(a),y-70*s*Math.sin(a),60)}); }
    r.push({tag:'one',pts:G.cluster(0,0,34*s,150)}); r.push({tag:'ch',pts:G.cluster(0,-620*s,34*s,150)}); return r; },
  moves:function(G){ var s=1.0; return [{tag:'one',at:2.2,dur:1.2,to:G.cluster(620*s,-520*s,40*s,200)},{tag:'ch',at:4.0,dur:1.0,to:G.cluster(0,0,34*s,200)},{tag:'ch',at:9.0,dur:1.0,to:G.cluster(-640*s,520*s,40*s,200)}]; },
  light:function(tag,t,p,C){ var R=t>=11.4;
    if(tag==='h0'){ if(R||t<0.4) return [C.ink3,0.6]; if(t<2.4) return [C.amber,1]; if(t<4.8) return [C.ink3,0.6]; if(t<9.6) return [C.amber,1]; return [C.ink2,0.8]; }
    if(tag[0]==='c'){ var i=+tag[1]; var t0=5.4+i*0.5; var on=t>=t0+0.4&&!R; return [on?C.amber:C.ink3, on?1:0.55]; }
    if(tag[0]==='l'){ var i=+tag[1]; var t0=5.4+i*0.5; if(R||t<t0) return [C.line2,0]; var u=Math.min(1,(t-t0)/0.4); if(t>=9.6) return [C.line2,0]; return [p.u<=u?C.amber2:C.line2, p.u<=u?0.9:0]; }
    if(tag==='one'){ if(R||t<0.4) return [C.amber2,0]; return [C.amber2, t<2.2?0.9:Math.max(0,0.9-(t-2.2)*0.9)]; }
    if(tag==='ch'){ if(R||t<4.0) return [C.amber,0]; if(t<9.0) return [C.amber,0.95]; return [C.amber,Math.max(0,0.95-(t-9.0)*1.1)]; }
    return [C.line2,0]; }
};

export const s06b: Cfg = { W: 800, H: 800, N: 2400, T: 11,
regions:function(G){ var s=1.0; var r=[]; r.push({tag:'md',pts:G.hex(-170*s,40*s,110*s,320)}); var x=G.cluster(-170*s,40*s,90*s,360); x.forEach(function(q){q[2]=Math.random();}); r.push({tag:'mdx',pts:x});
    r.push({tag:'api',pts:G.hex(170*s,40*s,110*s,320)}); return r; },
  moves:function(G){ var s=1.0; return [{tag:'mdx',at:6.0,dur:1.0,to:G.cluster(170*s,40*s,80*s,300)}]; },
  light:function(tag,t,p,C){ var R=t>=10.4;
    if(tag==='md'){ if(R||t<0.4) return [C.ink3,0.6]; if(t<5.2) return [C.ink3,0.7]; return [C.alert, Math.max(0,0.8-(t-6.0)*0.8)]; }
    if(tag==='mdx'){ if(R) return [C.alert,0]; var k=p.u<0.33?0:p.u<0.66?1:2; var t0=2.6+k*0.6; if(t<t0) return [C.alert,0]; if(t<6.0) return [C.alert,0.7]; return [C.amber, 0.6]; }
    if(tag==='api'){ if(R||t<6.0) return [C.ink3,0]; return [t>=6.8?C.amber:C.ink3, 1]; }
    return [C.line2,0]; }
};

export const CFGS: Record<string, Cfg> = { s01b, s02a, s03b, s04b, s05b, s06b };
/** the option chosen for each service (service id to scene key); set in scripts/port-hybrid.py */
export const PICK: Record<string, string> = {"01": "s01b", "02": "s02a", "03": "s03b", "04": "s04b", "05": "s05b", "06": "s06b"};
